var app=angular.module("myModule",[])
        .controller("myController",function($scope){
            $scope.students=[
                {
                    name:"tanya",
                    grade:"A",
                    subjects:["hindi","engilsh"]
                },
                {
                    name:"vanya",
                    grade:"C",
                    subjects:["maths","engilsh","french"]
                },
                {
                    name:"anya",
                    grade:"A-",
                    subjects:["computers","german"]
                }
            ]
            $scope.something="list.html"
        });